### ISSUE TITLE
update to match new Ego api

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-api#114]
Ego's api has changed (or will soon?) slightly, we need to update to match up.
(nothing will break if we don't because the old api is just being deprecated, but we are planning to remove it eventually)

https://github.com/overture-stack/ego/pull/420

**Comment by hlminh2000** [comment]
if token still shows up in QA and regenerate is still working, the update worked ;)

**Comment by rosibaj** [comment]
tested - token regenerate is working fine! thanks @hlminh2000
