### ISSUE TITLE
Include all clinical schema fields in schema list

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/platform-api#122]
The UI needs a list of all fields to be displayed in the submission table .  Currently, only the submitted fields in a file are shown on the UI.  If an optional field is NOT in the TSV, then it will not be submitted. 

To do this, the clinical service exposes this using anew flag in the /schema/list api.

## Possible Implementation

Show the fields regardless of where submitted

**Comment by rosibaj** [comment]
@kcullion lets work out a design on this!

**Comment by rosibaj** [comment]
Closing as this was decided as not needed - see #971 above
