### ISSUE TITLE
Graphql Schema design for program donor dashboard

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#133]
Get the data from the donorSubmission summary indices for the dashboard into the Gateway API
- design the GraphQL schema to match UI expectations
- ~~write resolvers to translate ES to GraphQL~~

**Comment by hlminh2000** [comment]
@rosi The Elasticsearch connection got complicated by the need to handle password. Added a separate ticket for this: https://github.com/icgc-argo/platform-api/issues/168

The schema design can be previewed at the normal graphql api

**Comment by rosibaj** [comment]
Noticed an inconsistent query parameter for programs:
`shortname` and `programid`: 
![image](https://user-images.githubusercontent.com/15824252/77202437-bd487c80-6ac4-11ea-9b97-b8038e1fb6f9.png)

Discussed with @hlminh2000; will use `shortname` for api consistency

**Comment by rosibaj** [comment]
lgtm on qa  thanks @hlminh2000
