### ISSUE TITLE
🐛 API Token doesn't generate in the dev environment, instead loading forever

### ISSUE THREAD

**Issue by P-Saha** [icgc-argo/platform-api#145]
## Describe the bug
API Token doesn't generate in the dev environment, instead loading forever with the network response having an error of keys.map not being a function.

## Steps To Reproduce
Go to https://platform-ui.dev.argo.cancercollaboratory.org/user
Generate API Token
In inspect element, the error of "keys.map is not a function" is shown.

![Screen Shot 2020-02-19 at 2 01 09 PM](https://user-images.githubusercontent.com/19506039/74866138-55b1dc80-5320-11ea-88a4-80adeabde908.png)

**Comment by joneubank** [comment]
Can reproduce. Issue is that the gateway tries to delete existing api key before generating new one, but the code breaks in the delete method if there are no keys for the user.

**Comment by joneubank** [comment]
Update: The cause isn't when the user has no keys, it is all cases - the API in EGO for Api Keys has changed and the EGO service in the Gateway wasn't updated to match.

This is an issue with`deleteKeys` and `getEgoAccessKeys`. The other methods in the Ego service file should also be checked for issues.

**Comment by rosibaj** [comment]
can generate keys in both dev and qa - this lgtm!
