### ISSUE TITLE
Implement filters in Donor Dashboard Table

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/platform-api#190]
Currently `programDonorSummaryEntries` query has a `filters` variable but filters has not been implemented yet.

Wiki page: https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs

## Detailed Description
When the user clicks on the filter icon in the column header, the filter will open, they can cancel or hit that filter icon again to close the filter.

There are three cases that UI needs to be able to query for:
**Checkboxes** (there seems to be some aggregatin here too)
Zeplin: stars: https://zpl.io/2jJzzGx
Core field status: https://zpl.io/25B77Lj
Sample Status: https://zpl.io/brZDd1O
Raw Read Status: https://zpl.io/2jJzAA4
Alignment and Sanger VC: https://zpl.io/bzZ4KOl
Processing:https://zpl.io/anJk49l
![image](https://user-images.githubusercontent.com/34698315/79461013-98600000-7fc3-11ea-8a85-2a938264e962.png)

**Search**
Zeplin: Donor ID: https://zpl.io/agJwwjR
![image](https://user-images.githubusercontent.com/34698315/79460877-6ea6d900-7fc3-11ea-92fa-feb5f90efe3b.png)

**Range**
Zeplin: Extended field status: https://zpl.io/aXv0lgl
<img width="216" alt="Screen Shot 2020-04-24 at 12 00 14 PM" src="https://user-images.githubusercontent.com/18424138/80232633-36d30d80-8623-11ea-988e-54d47be6f77d.png">

## Possible Implementation
- figure out how to modify the api to support those changes
  - two changes needed.  Aggregations/buckets need to to be defined.  (ex make 100 a bucket) 
  - extend the graphql schema to provide aggregations for these given fields. 
- take the new api inputs and generate the correct queries to ES

**Comment by kcullion** [comment]
closing up this epic, as it's complete
