### ISSUE TITLE
🐛 Dashboard stat: wrong count for Donors with Tumour & Normal

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#198]
## Describe the bug
This count should be counting the Raw Reads submission (from song).  The calculation needs to be fixed from the API endpoint

<img width="687" alt="2020-04-27_1343" src="https://user-images.githubusercontent.com/18424138/80403423-8d438480-888d-11ea-94e7-d1fcc20446c0.png">

**Comment by rosibaj** [comment]
lgtm - seeing 0 on all values now! thanks @jaserud !!

**Comment by rosibaj** [comment]
confirmed on prod
