### ISSUE TITLE
Jira -> Gateway setup

### ISSUE THREAD

**Issue by wajiha-oicr** [icgc-argo/platform-api#206]
@rosibaj commented on [Thu Feb 27 2020](https://github.com/icgc-argo/platform-ui/issues/1137)

https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Contact+Page#ContactPage-IntegrationwiththePlatformContactPage 

Write the graphql query for creating helpdesk tickets in gateway

from @hlminh2000: for prod release, add the following env:
```
JIRA_REST_URI: https://extsd.oicr.on.ca/rest/servicedeskapi
JIRA_SERVICEDESK_ID: 9
JIRA_ADMIN_VAULT_CREDENTIALS_PATH: ...
```
Also needs the credential put in vault.

**Comment by rosibaj** [comment]
@hlminh2000 To deploy this ticket, something needs to happen with vault yes?
