### ISSUE TITLE
Update deprecated clinical endpoints

### ISSUE THREAD

**Issue by jaserud** [icgc-argo/platform-api#207]
Update deprecated clinical endpoints

## Detailed Description
These endpoints are deprecated in clinical, so they should be updated:
![image](https://user-images.githubusercontent.com/34698315/81832079-17d1e800-950c-11ea-850e-cefdf98ca784.png)

Endpoints to update:
- `​/submission​/schema​/list`
- `​/submission​/schema​/template/{template}`

## Possible Implementation
- Use the new endpoint as indicated in the swagger doc

**Comment by rosibaj** [comment]
@jaserud why will all of these be deprecated?

**Comment by jaserud** [comment]
@rosibaj we changed the setup in clinical in a recent refactor (https://github.com/icgc-argo/argo-clinical/issues/486). The main thing here is the wording of `schema` is miss leading when it should really be `dictionary`.

**Comment by jaserud** [comment]
I updated the description because there are only two enpoints to update.

**Comment by jaserud** [comment]
Graphql query relevant for this change:
```
query{
  clinicalSubmissionSchemaVersion
  clinicalSubmissionTypesList
}
```
Swagger endpoints:
- clinical/template/all
- clinical/template/{schema}

In UI these translate to the template downloads, any visible dictionary version and the list of clinical types on the left in the submission page

**Comment by andricDu** [comment]
Released and tested in prod.
