### ISSUE TITLE
Integrate Arranger API and ARGO Gateway

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#213]
This is based on the work in icgc-argo/roadmap#337, which allowed Arranger to export its search GQL, 

- [x] deploy and configure arranger in ARGO after changes 
- [x] point it at a basic mapping and some fake documents provided on wiki 
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=File+Repository+Specification

**Comment by hlminh2000** [comment]
for testing, can run a query like this:
```
{
  file {
    hits {
      total
    }
  }
}
```

**Comment by rosibaj** [comment]
@hlminh2000 Does this include aggregations as well?

**Comment by hlminh2000** [comment]
Yes, aggregations are a part of the `file` query :)

**Comment by rosibaj** [comment]
> Yes, aggregations are a part of the `file` query :)

how do? couldn't find in autocomplete?

**Comment by hlminh2000** [comment]
here's a more full featured query :) : 
```
{
  file {
    aggregations {
      analysis__analysis_type {
        buckets {
          key
        }
      }
    }
    hits {
      edges {
        node {
          data_type
        }
      }
    }
  }
}
```

**Comment by rosibaj** [comment]
Whats with the weird  double underscore ` analysis__analysis_id`?
