### ISSUE TITLE
🐛 should be PROGRAM_ID not STUDY_ID

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#253]
In the file repository, there `program_id` field is mislabeled. 

`study_id` comes  from song, but it should be transformed to be consistent with the rest of the Argo API. 

![image](https://user-images.githubusercontent.com/15824252/84536708-6bc31e80-acbc-11ea-897d-d1323b19eacc.png)

**Comment by rosibaj** [comment]
- not very confident of doing a transformation in graphql only.

- One complication I can see right now is in the sqon, where all the field references are expecting to be Elasticsearch document fields. So if we just change graphql field without the underlying mapping, there’ll be a discrepancy between the graphql fields and the sqon. 
- So without changing the underlying mapping, I’m not sure there’s anything we can (or should) do there… If we really need this transformation without a mapping change, it should be an arranger configuration feature, which really won’t be done in time.

- An alternative to doing this in any application layer (gateway or arranger), is we can add a program_id field to the mapping, without removing the study_id field, that way the UI can run its queries and build sqons on program_id rather than study_id, then I can look into whether there’s a way to hide study_id in the gateway schema

**Comment by rosibaj** [comment]
https://github.com/overture-stack/maestro/issues/158

**Comment by kcullion** [comment]
Spoke to @joneubank and we will close this as it's more work than what it's worth.

` changing it will necessarily involve choosing where to stop changing it. it makes sense that the public interface would use program but unfortunately that means its a change in the file-centric index which relies changing code all the way back to file service…its more trouble than its worth i think`
