### ISSUE TITLE
Rate-limiting the gateway-api - Architecture Plan 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#269]
We have some ideas on how to protect our api through rate-limiting: 

- Use complexity score to limit 
- Select an in-memory db to build a hash table for rate limiting 
-  This is specific to graphQL;  It does not have the expertise to designate the differences between 
- to build comprehensive tables, the IT F5 is not large enough

## Expected Outcome 
- [ ] Wiki page of architecture and plan

**Comment by hlminh2000** [comment]
Architecture plan document created at: https://wiki.oicr.on.ca/display/icgcargotech/Platform+Gateway+Rate+Limiting
