### ISSUE TITLE
🐛 Stats break sometimes on File Repository

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#275]
## Describe the bug
First Incidence:
1.  go to File Repo, 
2. select OCCAMS-GB, CNV & Sequencing Reads in exactly that order.  Numbers at the top spin for 20 seconds and eventually returned 0.  
3. Clicking in the order of CNV, Sequencing Reads, OCCAMS-GB resulted in same behavior.

![image](https://user-images.githubusercontent.com/15824252/85335467-100e4780-b4ab-11ea-88be-9b21b0128235.png)

https://platform.icgc-argo.org/repository?filters=%7B%22content%22%3A%5B%7B%22content%22%3A%7B%22field%22%3A%22data_category%22%2C%22value%22%3A%5B%22Copy+Number+Variation%22%2C%22Sequencing+Reads%22%5D%7D%2C%22op%22%3A%22in%22%7D%2C%7B%22content%22%3A%7B%22field%22%3A%22study_id%22%2C%22value%22%3A%22OCCAMS-GB%22%7D%2C%22op%22%3A%22in%22%7D%5D%2C%22op%22%3A%22and%22%7D 

Second Incidence (Jul 27, 2020)
1.  go to File Repo, 
2. select LUCA-KR & VCF  in exactly that order.  (Url: 
https://platform.staging.icgc-argo.org/repository?filters=%7B%22content%22%3A%5B%7B%22content%22%3A%7B%22field%22%3A%22file_type%22%2C%22value%22%3A%22VCF%22%7D%2C%22op%22%3A%22in%22%7D%2C%7B%22content%22%3A%7B%22field%22%3A%22study_id%22%2C%22value%22%3A%22LUCA-KR%22%7D%2C%22op%22%3A%22in%22%7D%5D%2C%22op%22%3A%22and%22%7D

 Sometimes it will load, but sometimes it will spin forever.  Eventually the page crashed:
![image](https://user-images.githubusercontent.com/15824252/88590829-5a925f00-d029-11ea-9ece-a336b9edddb8.png)
![image](https://user-images.githubusercontent.com/15824252/88590794-48b0bc00-d029-11ea-93ac-b283f99e51ae.png)
![image](https://user-images.githubusercontent.com/15824252/88590903-7dbd0e80-d029-11ea-8c08-03f6168d5ecb.png)

## Expected behaviour
Stats should resolve 

## Potential 
https://www.ionos.ca/digitalguide/hosting/technical-matters/err-connection-reset/

**Comment by rosibaj** [comment]
@hlminh2000 is this still happening or was it a momentary blip?

**Comment by hlminh2000** [comment]
I don't think I've observed this... just tried to follow the steps on both prod and QA but not reproducible, since `Raw CNV Calls` filters out `Sequencing Reads`, I wasn't able to put the repo into that state...

**Comment by rosibaj** [comment]
closing as thi sis no longer observed.
