### ISSUE TITLE
Feature Request: Alert API for Platform Banner

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#282]
We need to develop the alert API response to feed into the update banners: 

The alert component for the platform-api expects this api response:
```
[{
  id: id
  level: AlertLevel;
  title: string;
  message?: string;
  dismissable: boolean;
},
...]
```
Type `AlertLevel` = `'error' | 'warning' | 'info'`

- ability to add the alert
- alert delivered by gateway

## Implementation 

We don't really need durable storage for the banner.  We will use a env vriable and github:
- Have a banner information file, with the editable banner variable.  
- Make a config in helm chart; job in jenkins to update the values. 
- Read ENV var from ENV valu. ENV value is passed in from git thru helm.  
- Jenkins rolling-restart and a job for banner deploy. 

The workflow for BA or bioinformatics team to add a banner will be to make a PR to update Banner, go to jenkins and deploy button for banner job. 

## Expected Behavior from this ticket 
- [ ] Add the endpoint/resolver to the GraphQL API that returns the expected response from an environment variable.

**Comment by samrichca** [comment]
query BANNERS {
  banners {
    id
    level
    title
    message
    dismissable
  }
}

**Comment by rosibaj** [comment]
@samrichca I need a software version label on this ticket before i can move forward please!
