### ISSUE TITLE
File repo: manifest program_id column

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#283]
On File Repo, the Manifest has `project_id` as its last column.  Should update to `program_id`.
![image](https://user-images.githubusercontent.com/15824252/86610998-10fbaa80-bf7c-11ea-96d0-ee42f101bcf1.png)

![image](https://user-images.githubusercontent.com/15824252/86610955-050fe880-bf7c-11ea-910e-c5a7d7c5942b.png)

**Comment by kcullion** [comment]
@rosibaj this looks good to me! was just thinking..was there anything to do on score end when uploading this manifest? I recall "program" is "project" there

**Comment by rosibaj** [comment]
@kcullion nope; score is just looking for the # of columns (not the names of columns!)
