### ISSUE TITLE
resolve new security errors 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#289]
![image](https://user-images.githubusercontent.com/15824252/88589966-f327df80-d027-11ea-83c0-1c1e35c62e9d.png)

**Comment by rosibaj** [comment]
@hlminh2000 can we get this released to qa?

**Comment by hlminh2000** [comment]
my bad! it is out in QA already, I forgot to move ticket!

**Comment by rosibaj** [comment]
@hlminh2000 is there a version number tag for this?
