### ISSUE TITLE
Logs arent actually logging?

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#290]
While debugging an issue #275 with Minh, we found that the logs were not recording graphql requests past the last 7 days.  this coincided with the day that the pod was spun up (potentially from the release).

We should be able to access logs to debug issues easier

**Comment by hlminh2000** [comment]
this is likely because we are relying on the logging that happens during query complexity computation, which might be cached and bypassed by the library. We should introduce a request log at the http level with a log middleware.

**Comment by akachru-github** [comment]
What was the timing on this? Was this right after the IT shutdown?
Also, what logs are we referring to here (assuming this is for Platform prod env)? 
@henro001 @yalturmes

**Comment by rosibaj** [comment]
@akachru-github This ticket was logged the day i observed this happening with Minh ( Jul 27th).   

The logs that we were looking for were the graphql requests from the platform api.  As i saw errors happen, minh was looking for them to be logged to see what was happening.  

@hlminh2000 any additional details?

**Comment by rosibaj** [comment]
Verified on Sep 03, 2020.  logs are still not visible in pod, so something is not being translated. 

@akachru-github can i pass this to you to have the devops team take a look at?

**Comment by akachru-github** [comment]
Will add it to the backlog.

**Comment by rosibaj** [comment]
Its been too long and the situation in no longer reproducible.  I will close this ticket and in future if we expereince the issue again will re-log this ticket.
