### ISSUE TITLE
implement metadata access control through arranger integration 

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-api#294]
- Updates to platform-api: integrate with new Arranger feature to apply default SQON on every request (awaiting feature development).
- update the arranger metadata to know about the new field 
- enable with a feature flag so it can be disabled in production until ready 

## Detailed Description
This is to support this spec: https://wiki.oicr.on.ca/display/icgcargotech/File+Metadata+Access+Control

## Possible Implementation
Use the updates from ego-token-utils above. Some pseudo-code (pending arranger investigation & implementation, please do a better job):

```ts
      const ownProgramFilter = {
        // filters out files in EMBARGO_OWN_PROGRAM stage from OTHER programs
        op: "and",
        content: [
          {
            op: "in",
            content: {
              field: "release_state",
              values: ["EMBARGO_OWN_PROGRAM"],
            },
          },
          {
            op: "not",
            content: [
              {
                op: "in",
                content: {
                  field: "study_id",
                  values: [...usersProgramIds],
                },
              },
            ],
          },
        ],
      };
      const userAccessLevel = getFileMetadataAccessLevel(jwt)
      const { schema: argoArrangerSchema } = (await createProjectSchema({
         getServerSideFilter: () => {
          switch (userAccessLevel) {
            case "DCC_MEMBER":
              return {
                // sees everything
                op: "not",
                content: [],
              };
            case "FULL_PROGRAM_MEMBER":
              return ownProgramFilter;
            case "ASSOCIATE_PROGRAM_MEMBER":
              return {
                op: "and",
                content: [
                  ownProgramFilter,
                  {
                    // filters out files in EMBARGO_FULL_PROGRAMS from OTHER programs
                    op: "and",
                    content: [
                      {
                        op: "not",
                        content: [
                          {
                            op: "in",
                            content: {
                              field: "study_id",
                              values: [...usersProgramIds],
                            },
                          },
                        ],
                      },
                      {
                        op: "in",
                        content: {
                          field: "release_state",
                          values: ["EMBARGO_FULL_PROGRAMS"],
                        },
                      },
                    ],
                  },
                ],
              };
            default:
              // public user, logged in or not
              return {
                op: "not",  // double negative --> positive
                content: [
                  {
                    op: "in",
                    content: {
                      field: "release_state",
                      values: ["PUBLIC"],
                    },
                  },
                ],
              };
          }
        },
      })) as { schema: GraphQLSchema };
```

Conceptual, this is to achieve the following access model:
![image](https://user-images.githubusercontent.com/11821106/90674814-a51d8a80-e227-11ea-9d29-8fe16738a57a.png)

![image](https://user-images.githubusercontent.com/11821106/91361623-ba199100-e7c6-11ea-8124-d9f4a4bf7922.png)

## Expected Outcome 
As a user, I can login and see only the data that i have permission to from an API query 

To test this: 
- querying the api as a full member with no program access, see full/associate/queued data AND public data
- querying the api as a associate program member, see my program data AND associate/queued from other programs AND public data

**Comment by rosibaj** [comment]
@blabadi @ciaranschutte i checled with Minh, and this can go to QA

```
Yes! It's feature flagged so need an env update if you wanna test. It'll only work with the fake data cause real data doesn't have release stage yet
```

Would one of you be able to help moving this forward?

**Comment by blabadi** [comment]
created this PR: https://github.com/icgc-argo/platform-api/pull/350

**Comment by blabadi** [comment]
tests failed twice, and different tests each time, they seem flaky to me and related to the elastic search container lifecycle

**Comment by blabadi** [comment]
the PR branch test passed but the branch tests failed, so definitely  inconsistent 
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/4084e636-fe51-46c9-a27c-f80299c95926)

**Comment by rosibaj** [comment]
@hlminh2000 can we get this moved to the dev enviroment? Are there any blockers here?

**Comment by rosibaj** [comment]
- Tests are not stable. They are complex and spinup an ES with fake data.  Unknown why the test is failing. 
- Feature is working fine. 
- This is blocking the CI flow. 
- this is still behind a feature flag. 
-

**Comment by hlminh2000** [comment]
failing test has been disabled in CI, latest has been released to QA. Access control is behind feature flag, so no behavior change is expected out of this release.
