### ISSUE TITLE
Validation endpoint

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/platform-api#32]
Executes any validations that exist
Sets the workspace into a valid or invalid state
Validation for donor (rules will be implemented)

**Comment by rosibaj** [comment]
need clinical to be released to qa - will be done next week

**Comment by rosibaj** [comment]
Tested in Postman - Was able to validate a clinical submission.  

Found https://github.com/icgc-argo/argo-clinical/issues/154

**Comment by rosibaj** [comment]
Looks great!  Thanks @jaserud @joneubank !!!
