### ISSUE TITLE
🐛 Server-Side Metadata Query not functioning as expected - Aggregations

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#364]
## Describe the bug
Follow-up feedback to #294 , also in conjunction with https://github.com/icgc-argo/platform-ui/issues/1764 

## Steps To Reproduce
Environment: QA 
Test programs to look at: `MINHDASH-CA` (*Associate* level)  and `DASH-CA` (*Full* membership level)
Steps to reproduce the behaviour:
1. Go to the QA environment.  Add yourself as a DATA SUBMITTER to `MINHDASH-CA` and make sure your user belongs to no other programs.  When you login after accepting the invitation, you should be able to see the File Repository.  As an a associate program member logged in you should be able to see the yellow facet at the top. This facet should display: 
- all of the release statuses
- When filtered on FULL, only MINHDASH-CA should be present 
- - see my program data AND associate/queued data from other programs AND public data
2. In actuality, when i click on this, i get an empty result: 
![image](https://user-images.githubusercontent.com/15824252/106025459-c0be7400-6096-11eb-84d3-1a57cbbc0152.png)

Seeing as MINH-DASH-CA does not have any files `0` is the correct result, but the facet should not be reporting any number.
3. Filter on just DASH-CA. The number of files on DASH-CA indicated that there are 539;  When filtered on DASH-CA, the yellow facet shows > the 539 total count of files. 
![image](https://user-images.githubusercontent.com/15824252/106025900-3591ae00-6097-11eb-966a-fd5fe003d635.png)
Filtering on one of these suspect numbers results in a blank query: 
![image](https://user-images.githubusercontent.com/15824252/106025952-4510f700-6097-11eb-815d-1314b52e20cd.png)

## Expected behaviour
I am testing from the UI, assuming that the API behavior is as expected (i.e just piping to UI)
To test this:
- [ ] querying the api as a full member with no program access logged in, see `my program data AND see full/associate/queued data from other programs  AND public data`
- [ ] querying the api as a associate program member logged in, `see my program data AND associate/queued data from other programs AND public data`
- [ ] querying the api as a public member logged in, see `only publicly released data` 
- [ ] Resolve the `blank value` on the facet.  This should not be blank. Identify if this is a component issue or a facet issue. 
![image](https://user-images.githubusercontent.com/15824252/105873244-4673ee00-5fc9-11eb-939a-de23f89e3b8d.png)

**Comment by ciaranschutte** [comment]
blank facet is due to data having a `__missing__` value.
solution implemented is to filter this out.

we may also want some kind of constraint server side.

**Comment by rosibaj** [comment]
@joneubank considering the impleications of a `_missing_` value; that would mean a file is NOT marked with a release stage.  We would want to make sure that this does not happen in the data itself, but additionally, what @ciaranschutte suggested may also be prudent (i.e if it happens, make sure that cannot be displayed?)

**Comment by joneubank** [comment]
Ideally we wouldn't have this in our data, but if it is possible then we need a way to handle it. Filtering it out is fine. Alternately setting a default value.

**Comment by ciaranschutte** [comment]
not just piping to the frontend.
issues with server side filter SQON filters not returning correct results

Example:
This works
```
{
  "filters": {
    "op": "and",
    "content": [
      {
        "content": {
          "field": "study_id",
          "value": "DASH-CA"
        },
        "op": "in"
      },
      {
        "op": "not",
        "content": [
          {
            "op": "and",
            "content": [
              {
                "op": "not",
                "content": [
                  {
                    "op": "in",
                    "content": {
                      "field": "study_id",
                      "value": ["TEST-CA", "TEST-CA"]
                    }
                  }
                ]
              },
              {
                "op": "in",
                "content": {
                  "field": "release_stage",
                  "value": ["OWN_PROGRAM"]
                }
              }
            ]
          }
        ]
      }
    ]
  }
}
```
but adding a program filter to it breaks the Release Stage Facet eg:
```
{
  "filters": {
    "op": "and",
    "content": [
      {
        "content": {
          "field": "study_id",
          "value": "DASH-CA"
        },
        "op": "in"
      },
      {
        "op": "not",
        "content": [
          {
            "op": "and",
            "content": [
              {
                "op": "not",
                "content": [
                  {
                    "op": "in",
                    "content": {
                      "field": "study_id",
                      "value": ["TEST-CA", "TEST-CA"]
                    }
                  }
                ]
              },
              {
                "op": "in",
                "content": {
                  "field": "release_stage",
                  "value": ["OWN_PROGRAM"]
                }
              }
            ]
          }
        ]
      }
    ]
  }
}

```

**Comment by ciaranschutte** [comment]
Work done already:
(1) hide facet values that are not permissible eg. `Full` for an associate user 
(2) use correct context property and extract ego token so server side filter is created successfully

**Comment by joneubank** [comment]
Sorting out aggregations through filter manipulation in arranger may be possible but will end up being extremely complex. In our situation, we have two filters on a given property, one from the user selections and one from the access controls, and we want to apply one but not the other to the aggregations but both to the results.

Introducing a way for arranger to handle this generically and ensuring that there were no edge cases was likely to be more trouble than it was worth, but there was a simpler solution.

We are adding new properties to the file documents, `meta.embargo_stage`, `meta.release_state` and `meta.study_id`. These properties will have the same values as the properties on the root level of the file document. The access filter will use these properties, and the aggregation facet used for user filtering and the UI will use the existing properties. This way, there is no conflict, no need to do partial filters on aggregation, etc. All the complexities go away.

No changes are being made to arranger. This is handled in the API only now.

**Comment by rosibaj** [comment]
testd on other tickets.
