### ISSUE TITLE
GQL Query + Resolver: Molecular Data Chart 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#371]
Once the expected index to develop against has been added to the ES cluster, develop the expected GQL query 
- [ ] Query should take the variables: 
- Program ID
- Data range, in Unix epoch
- Number of data points (7 right now)
- Chart type (clinical or molecular)

- [ ] Resolver should take the inputs and complete the resolution of data to return the expected buckets of data with counts for each analysis type. 
To resolve this data, a query should be done against Elasticsearch index defined in #726, #727

Successful API response:
- Number of committed donors
- Lines:
  - Title (string for molecular & null for clinical)
  - Points:
    - Date (last day in range, in Unix epoch)
    - Donors

API Resonse Errors:

- Days in date range < # data points
- Program ID not found
- No data? Or just send back all Y coords as 0?

## Expected Outcome 
In the platform-api gql, I can query a Program, date range,  and set of` anlaysis_type`s and get donor count results returned.

**Comment by samrichca** [comment]
errors you can get:
- wrong input types
- missing inputs
- days between "to" and "from" < bucket count
- bucket count is a negative number
- "to" is before "from"
- donor fields missing or not the right ones ("createdAt","mutectFirstPublishedDate", "alignmentFirstPublishedDate","rawReadsFirstPublishedDate", "sangerVcsFirstPublishedDate")
-

**Comment by rosibaj** [comment]
Confirme don prod - data is reindexed and is visible on program dashboards!
