### ISSUE TITLE
Update Arranger configurations to match the new mapping 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#392]
Using the new mapping that was done: https://github.com/icgc-argo/argo-metadata-schemas/tree/master/mappings
- update the Arranger configuration to match this mapping 
- There are 4 config files; three need to be updated. 
-- Arranger mostly builds its API off of the mapping, but the `extended config` needs to be updated  with things like Display name, array values etc

**Comment by samrichca** [comment]
I can't connect this PR from the schemas repo through ZenHub so here's the link:
https://github.com/icgc-argo/argo-metadata-schemas/pull/58

**Comment by samrichca** [comment]
discussed with Jon

I have to update mapping in platform-api on the `file` type
