### ISSUE TITLE
implement programDonorSummaryEntries Filter: Core Completion 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#416]
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/c50a304c-666b-4c6a-880e-00e33f2f8105)

- [ ] extend the schema 
- [ ] build the resolver for the aggregation 
  - Translate the complete/incomplete/empty to the ES buckets/query

**Comment by Buwujiu** [comment]
@rosibaj 
Please refer to the follow query for testing: 
the field for filtering core completion is `coreDataPercentAggregation`, there are 3 enum values: `NO_DATA`, `COMPLETE`, and `INCOMPLETE`.
```
# Write your query or mutation here
query{
  programDonorSummaryEntries (
    programShortName: "ROSI-RU",
    sorts:{
      field:donorId, order: asc
    },
    filters: [
      { 
        field: combinedDonorId,
      	values: ["donor"]
      },
      {
        field: coreDataPercentAggregation,
        values: ["COMPLETE", "INCOMPLETE", "NO_DATA"]
      }
      
     
]
  ) {
  	id
    donorId
    submitterDonorId
    programShortName
    submittedCoreDataPercent
   
  }
}
```

**Comment by rosibaj** [comment]
Testes Jul 08 2021, 5:43

@Buwujiu LGTM!  I tested with 2 programs, with just the `core completion` filter applied, and also with the other fields filters applied and got all the correct expected results. 

moving forward!
