### ISSUE TITLE
implement programDonorSummaryEntries Filter: Samples

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#417]
https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.1TableDataFields,Filters,&DataSources

- When filtered on INVALID, any tumour or normal cell with a count of 0 (invalid) should show in the table.
- When filtered on VALID, any donor that has at least one tumour/normal pair will be filtered.
![image](https://user-images.githubusercontent.com/15824252/125806935-a596504d-8877-457c-b4f2-7170d6a3f897.png)

**Comment by Buwujiu** [comment]
Filter is available in QA, added a new field `registeredSamplePairs` for filtering by valid/invalid sample pairs, please use the following query: 

```
query{
  programDonorSummaryEntries (
    programShortName: "ROSI-RU",
    sorts:{
      field:donorId, order: asc
    },
    filters: [
      {
        field: combinedDonorId,
        values: ["donor"]
      },
      {
        field: registeredSamplePairs,
        values: ["VALID", "INVALID"]
      }
    ]
  ) {
  	id
    donorId
    submitterDonorId
    programShortName
    submittedCoreDataPercent
   	publishedNormalAnalysis
    publishedTumourAnalysis
  }
}
```

**Comment by rosibaj** [comment]
tested Aug 25, 2021 

lgtm thank  you @Buwujiu !!!
