### ISSUE TITLE
Implement the Dashboard filter: Workflow Column Alignment 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#427]
## Specs 
- Filter should allow free text typing.  No autocomplete or interaction. 
- User can select from the values `Completed`, `In Progress`, `Failed`, `No Data`
- `Completed` = aligned > 0
- `Failed` = failed > 0 
- `In Progress` = in prpogress > 0
- `No Data` = all of the above three = 0

![image](https://user-images.githubusercontent.com/15824252/124018636-0f5d9a80-d9b6-11eb-8a5a-45948c8d577b.png)

## Implementation
- [ ] Implement filters in programDonorSummaryEntries query for `Alignment`
- [ ] extend the schema 
- [ ] build the resolver

**Comment by Buwujiu** [comment]
Filter is available in QA, added a new field `alignmentStatus` for alignment filtering, please use the following query
```
query{
  programDonorSummaryEntries (
    programShortName: "ROSI-RU",
    sorts:{
      field:donorId, order: asc
    },
    filters: [
      {
        field: combinedDonorId,
        values: ["donor"]
      },
      {
        field: registeredSamplePairs,
        values: ["VALID", "INVALID"]
      },
      {
        field: rawReads,
        values: ["INVALID", "VALID"]
      },
      {
        field: alignmentStatus,
        values: ["FAILED", "IN_PROGRESS", "NO_DATA", "COMPLETED"]
      }
    ]
  ) {
  	id
    donorId
    submitterDonorId
    programShortName
    submittedCoreDataPercent
   	publishedNormalAnalysis
    publishedTumourAnalysis
  }
}
```
