### ISSUE TITLE
Implement the Dashboard filter: Raw Reads Column

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#440]
https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.1TableDataFields,Filters,&DataSources

- When filtered on INVALID, any tumour or normal cell with a count of 0 (invalid) should show in the table.
- When filtered on VALID, any donor that has at least one tumour/normal pair will be filtered.

**Comment by Buwujiu** [comment]
Filter is available in QA, a new field `rawReads` is added to the filter, please use the following query: 

```
query{
  programDonorSummaryEntries (
    programShortName: "ROSI-RU",
    sorts:{
      field:donorId, order: asc
    },
    filters: [
      {
        field: combinedDonorId,
        values: ["donor"]
      },
      {
        field: registeredSamplePairs,
        values: ["VALID", "INVALID"]
      },
      {
        field: rawReads,
        values: ["INVALID", "VALID"]
      }
      
    ]
  ) {
  	id
    donorId
    submitterDonorId
    programShortName
    submittedCoreDataPercent
   	publishedNormalAnalysis
    publishedTumourAnalysis
  }
}
```

**Comment by rosibaj** [comment]
lgtm thank you @Buwujiu!!!

**Comment by rosibaj** [comment]
confirmed on prod release September 02, 2021
