### ISSUE TITLE
Implement the Dashboard Filter: Sanger VC Column

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#449]
## Specs 
- Filter should allow free text typing.  No autocomplete or interaction. 
- User can select from the values `Completed`, `In Progress`, `Failed`, `No Data`
- `Completed` = aligned > 0
- `Failed` = failed > 0 
- `In Progress` = in progress > 0
- `No Data` = all of the above three = 0

![image](https://user-images.githubusercontent.com/15824252/124018636-0f5d9a80-d9b6-11eb-8a5a-45948c8d577b.png)

## Implementation
- should mimic the other wf columns (alignment)

**Comment by Buwujiu** [comment]
Please refer to this query for added filter:
```
programDonorSummaryEntries (
    programShortName: "ROSI-RU",
    sorts:{
      field:donorId, order: asc
    },
    filters: [
       {
        field: sangerVCStatus
        values: ["IN_PROGRESS", "COMPLETED", "FAILED", "NO_DATA"]
      }
]
  ) {

    donorId
    submitterDonorId
    programShortName
    submittedCoreDataPercent
    registeredNormalSamples
    registeredTumourSamples
    publishedNormalAnalysis
    publishedTumourAnalysis
    releaseStatus
    sangerVcsCompleted
    sangerVcsRunning
    sangerVcsFailed
    mutectCompleted
    mutectRunning
    mutectFailed
   
  }
}
```
