### ISSUE TITLE
Retrive the score-url as part of the gateway requests 

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/platform-api#456]
- The gateway requires a `repositories.url` to connect to the correct Score server during requests for a file. 
- The Score client actually requires a Score URL to download files.  
- We want it to have the reverse proxied URL: https://storage.rdpc.cancercollaboratory.org 
- 
## Detailed Description
For Argo, we are "reverse-proxying" the RDPC Scores in the platform gateway, so we need the correct score url in order to proxy download requests. 

## Possible Implementation
- update maestro config values with the new URL 
- reindex all of maestro 

## Expected Outcome 
`/https://api.platform.icgc-argo.org/storage-api/download/` should be the url in the index

**Comment by joneubank** [comment]
Code changes to data center registry required to make score URL available: https://github.com/icgc-argo/data-centers-registry/commit/5fb30cb59ce9cce172972765596cad34d622fb1e
