### ISSUE TITLE
allow excluding sample registration downloading

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-api#492]
To support this request: https://github.com/icgc-argo/platform-ui/issues/2047, gateway api `/clinical/template/all` endpoint must be updated to allow excluding sample registration downloading.

**Comment by kcullion** [comment]
Tested this from the platform UI in staging, commented on this ticket: https://github.com/icgc-argo/platform-ui/issues/2047,

Just going to make a followup ticket to make sure this sample_registration file gets downloaded from here https://docs.icgc-argo.org/dictionary
