### ISSUE TITLE
File Entity: API for "Download" button for small downloads

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/platform-api#500]
- When logged in and the file is small enough, users should be able to download the file from the File Entity Page
- File size maximum: 100MB?
  - QC metric files, probably not larger than 100MB. 
  - @joneubank changed this to 5MB
- proxy to Score
  - grab URL from Score server (tells us where the file lives), redirect user to generated Score and download through the browser.

**Comment by b-f-chan** [comment]
@b-f-chan to help test

**Comment by kcullion** [comment]
tested with this ticket: https://github.com/icgc-argo/platform-ui/issues/2091
Looks great to me!
