### ISSUE TITLE
Extend API to include some program metadata

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#508]
As a followup to this ticket: https://github.com/icgc-argo/platform-ui/issues/2105
And the summary ticket for the donor entity page will need this program name too: https://github.com/icgc-argo/platform-ui/issues/1862 
![image](https://user-images.githubusercontent.com/18424138/158459031-bb13fabe-1ca3-4c38-a7af-fdd5210433ef.png)

Currently the program metadata requires authentication to access. We need to modify the api to allow public access to basic program summary fields.

For now we just want to expose the program `name` to the public on the donor and file entity pages, but we need to discuss what other fields to eventually expose so we can do this work all at once.

**Description (make public)
Name (make public)**
Commitment donors (keep private)
Submitted donors (keep private)
Genomic donors (keep private)
**Website  (make public)
Institutions (make public)
Countries (make public)
Processing Regions (make public)
Cancer types (make public)
Primary sites (make public)**
Membership type (keep private)
Users  (keep private)

This should be done after https://github.com/icgc-argo/program-service/issues/379, as part of the requirement for program entity page as well.

**Comment by Buwujiu** [comment]
Next step: 
how do we make data in program service accessible? 
- simple solution is we create an endpoint on program service that doesnt require auth so we can see program details from anywhere.
- ideal solution is this information gets indexed somewhere to be easily queryable without interacting with program service.
TODO - need to discuses solutions.

**Comment by Buwujiu** [comment]
Azher to set up swagger for easy interaction. But program service endpoint is ready.

**Comment by Buwujiu** [comment]
Tested query in QA and staging, however, the `countries` `institutions` `cancerTypes` `primarySites` `regions` are null. 
Expected behaviour: all the public fields should not be null. 

![Screen Shot 2023-05-08 at 9 37 26 AM](https://user-images.githubusercontent.com/8744047/236838645-a601d9f1-9aaf-4523-8c2c-d7cde3573128.png)

**Comment by Buwujiu** [comment]
Moving back to in progress

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!
