### ISSUE TITLE
Adding timestamp to the end of the manifest file name

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#515]
This is the API part that goes along with this ticket: https://github.com/icgc-argo/platform-ui/issues/2147

To make the file download more unique, we will add the timestamp to the end of the filename

**Comment by mistryrn** [comment]
Completed in https://github.com/icgc-argo/platform-api/pull/509

**Comment by kcullion** [comment]
I see the timestamp at the end of the file name in QA. Thanks!!

**Comment by kcullion** [comment]
timestamp works in staging
