### ISSUE TITLE
Reorder file ID in file repo in descending order

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#521]
As mentioned in: https://github.com/icgc-argo/platform-ui/issues/2109 this requires an API change

Issue:
```
OK so issue with sorting by file id, technically FL999 > FL1000 -- files above 999 are getting pushed to the back of the line, because of a quirk of how JavaScript works.
I can order the File IDs such that it starts at 999 and descending for now. Do we want that?
Getting it so file ids >999 display first is going to require extra logic on the API.
```
Solution:
`To get the correct file id order we basically need to sort by parseInt(file_id.slice(2)) -- so we are comparing 999 <> 1000 instead of FL999 <> FL1000`

**Comment by demariadaniel** [comment]
Pretty sure an update to `Platform API > src/routes/file-storage-api/handlers/entitiesHandler.ts` is the right place to do this.

**Comment by akachru-github** [comment]
- Change to file index required. File Manager change. 
- UI can request a sort by that property.

**Comment by kcullion** [comment]
@demariadaniel is there a way to show blue "descending order" band in the column by default? 
![image](https://user-images.githubusercontent.com/18424138/158249171-33ec4963-cea6-4b17-a6e4-388828858d7f.png)

**Comment by kcullion** [comment]
I see the correct file sort order and the blue sort indicator on the column in QA. Thanks @demariadaniel !

**Comment by b-f-chan** [comment]
@demariadaniel please tag with version

**Comment by kcullion** [comment]
sorted by file id in descending order in staging. works as expected
