### ISSUE TITLE
Calculate `percentageTumourAndNormal` to support UI Molecular Card

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-api#536]
The current donor dashboard UI `Donors with a DNA T | N Matched Pair` percentage is calculated as such: 
```
${Math.round( programDonorSummaryStats.percentageTumourAndNormal * 100 )
```
This might not be accurate as the definition of the percentage is changed to: 
<<Number of Donors with at least 1 T/N pair>>/ <<# donors committed>>

## Possible Implementation
Check the `ProgramDonorSummaryStats` API to see if `percentageTumourAndNormal` is in alignment with the new definition described above. 
If not, calculate the correct number for `ProgramDonorSummaryStats`. 

This is to support this UI change: 
https://github.com/icgc-argo/platform-ui/issues/2217

**Comment by b-f-chan** [comment]
@Buwujiu @kcullion - Just want to confirm, this ticket doesn't need to be feature-hidden, correct?

**Comment by Buwujiu** [comment]
Implemented in this pr: https://github.com/icgc-argo/platform-api/pull/555

**Comment by Buwujiu** [comment]
Removed `feature-hidden` label as no feature flag was added.
