### ISSUE TITLE
[API] Marking submitted File types with no data or with errors

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#540]
Clinical change: https://github.com/icgc-argo/argo-clinical/issues/758
- provide the graphQl interface to access the clinical API. 

**Related mockup**: https://zpl.io/p1rLJQl

![image](https://user-images.githubusercontent.com/18424138/159765848-9609d22f-326c-42fb-83b3-615be4ac4137.png)

**Comment by joneubank** [comment]
Notes on expanding our GQL Queries to include error data and be filterable by entity types:

```
# 1. Load Submitted Data
## Render Entities Tab Menu
## Show Entity Tabs with Errors
query {
  clinicalData(programShortName: $programShortName) {
    programShortName
    clinicalEntities {
      entityName
      hasErrors
    }
  }
}

# 2. Get Submitted Data for Initial Tab Donors
## This could be any tab, just our example will get donors
## page: number; pageSize: number; entityTypes: string[];
query {
  clinicalData(programShortName: $programShortName) {
    programShortName
    clinicalEntities (entityTypes) {
      entityName
      entityFields
      records (page, pageSize) {
        fields {
          name
          value
          error #string of error description, or null if no error
        }
      }
      hasErrors # boolean indicating if there are errors on the entity
      errors {
        count
        fieldName
        description
      }
    }
  }
}
```

**Comment by kcullion** [comment]
There seems to be some bugs with this API piece (as we see errors coming through on files that have no data submitted). Feedback recorded here: https://github.com/icgc-argo/platform-ui/issues/2327

**Comment by kcullion** [comment]
submitted data section is correctly hidden in staging, and going to the URL shows a 404.
