### ISSUE TITLE
[API] Donor Search: Look up by donor ids in submitted data

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#543]
- [x] Extend the API to be able to Filter by donor id/submitted donor id
- [x] Will need to ability to auto complete the search 
- [x] Will also need to look up based on multiple ids

Related mockups: https://zpl.io/XYDgAmM
![image](https://user-images.githubusercontent.com/18424138/159767926-2308d719-e75e-40b9-aa7b-41b86caf519f.png)

**Comment by lindaxiang** [comment]
Test and work:
- searching by DonorID and submitter_donor_id
- auto complete search works. I don't see the odd behaviour Edmund experienced
Does NOT work:
- sometimes the clear button (X) does not clear the results
- LIST button does not work for me, can't test multiple IDs

**Comment by Buwujiu** [comment]
Made a feedback ticket: https://github.com/icgc-argo/platform-ui/issues/2440.
This will remain in QA until 2240 is resolved.
