### ISSUE TITLE
Implement filters for RNA samples, raw reads, alignment

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-api#558]
Implement filters in `programDonorSummary` API on these RNA fields:
RNA samples
RNA raw reads
RNA alignment status

**Comment by b-f-chan** [comment]
@lindaxiang - Can you test this one?

**Comment by lindaxiang** [comment]
@Buwujiu @b-f-chan  tested in QA. Looks good. 
To be clarified, the filters are:
- rnaRegisteredSample. enum: [DATA_SUBMITTED, NO_DATA]
- rnaRawReads.  enum: [DATA_SUBMITTED, NO_DATA]
- rnaAlignmentStatus. enum:[COMPLETED, IN_PROGRESS, FAILED, NO_DATA]

**Comment by Buwujiu** [comment]
Feature not hidden, removing the feature-hidden label.

**Comment by b-f-chan** [comment]
Confirmed with @Buwujiu this is not hidden behind feature flag and she has removed the label as discussed

**Comment by lindaxiang** [comment]
Tested in Staging and looks good. @b-f-chan @Buwujiu
