### ISSUE TITLE
Security Upgrade: Major Upgrade

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-api#567]
Fix major security alerts based on the results of https://github.com/icgc-argo/platform-api/issues/550#issuecomment-1150234746

Exit Criteria:
- platform api works as expected
- should be no critical or hight security alerts after the upgrade

**Comment by demariadaniel** [comment]
PR to fix `critical` vulnerabilities + reduce `high` severity vulnerabilities
https://github.com/icgc-argo/platform-api/pull/657

Major updates to `graphql`, `jest` + `apollo` libraries will be required in the near future
