### ISSUE TITLE
🐛 Download all clinical data button is broken on dashboard

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#568]
## Describe the bug
The Download` All Clinical Data` button returns a 404 on Dev, QA and Prod

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to a program
2. Click on the download button
3 See error

![image (98)](https://user-images.githubusercontent.com/18424138/173687396-d413da90-b5d1-42ec-9a66-9a1c2501e2b0.png)

## Expected behaviour
This button used to download all of the submitted clinical data for the program 

From Jon in slack:
its definitely not being found
UI -> gateway (platform-api) -> clinical
but the gateway is sayign that endpoint is 404 not found
so start there, see if that route has been changed, it should be translating the request to another request to clinical

**Comment by demariadaniel** [comment]
PR here: https://github.com/icgc-argo/platform-api/pull/569

**Comment by b-f-chan** [comment]
@demariadaniel to tag with version label

**Comment by kcullion** [comment]
the download is working in production
