### ISSUE TITLE
Ability to download all templates

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#57]
Using the schema download, you can download individual schemas as files:

https://argo-gateway.qa.argo.cancercollaboratory.org/api-doc

We also need the ability to download a zipped file of all schema templates. 

![image](https://user-images.githubusercontent.com/15824252/65538648-c372ed00-ded5-11e9-99e5-bc7b39eead6d.png)

**Comment by rosibaj** [comment]
@jaserud the endpoint looks like its working now :) 

One small change - can we please name the downloaded file `argo_submission_templates.zip` instead of `all.zip`?

**Comment by jaserud** [comment]
:+1:  will do, this is an easy change

**Comment by rosibaj** [comment]
cool moving back to in progress till we get that change! thx!

**Comment by jaserud** [comment]
The file name has been updated in clinical release 0.9.6 and api 1.3.7

**Comment by rosibaj** [comment]
lgtm!  Thanks @jaserud !
