### ISSUE TITLE
[API] Donor Search: Look up by multiple donor ids in modal

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-api#595]
## Detailed Description
Add the ability to search by multiple donor ids in the search modal:
![Screen Shot 2022-09-06 at 4 32 16 PM](https://user-images.githubusercontent.com/8744047/188736785-3c9292f3-09a2-4dd2-b307-f3c1f8779cf1.png)

## Possible Implementation
2 UI tickets related to this:
- UI with queries: https://github.com/icgc-argo/platform-ui/issues/2270
- Static UI: https://github.com/icgc-argo/platform-ui/issues/2261

**Comment by daniel-cy-lu** [comment]
@Buwujiu Regarding to the version number, this is not a platform-api ticket. It is a platform-ui ticket. It has the version number of 1.116.0. How should we proceed?  Can I add 1.116.0 to this ticket or we need to change it from api to ui?

**Comment by Buwujiu** [comment]
@daniel-cy-lu if there is no api PR for this, we can just leave it as is.

**Comment by Buwujiu** [comment]
Since It is a platform-ui task, closing the issue.

**Comment by lindaxiang** [comment]
I input the following mixed Donor ID/Submitter donor ID, but only one donor is found and returned.
```
PD47028
PD45495
DO250542
```
