### ISSUE TITLE
Add DNA filters

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-api#610]
Related ticket for RNA filters: https://github.com/icgc-argo/platform-api/issues/512
Front-end ticket: https://github.com/icgc-argo/platform-ui/issues/2245
Requirements: https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.1TableDataFields,Filters,&DataSources

- Add a filter for tumor & normal registration. see `percentageTumourAndNormal`
- Add a filter for submitted matched pairs. see `matchedTNPairsDNA`  `donorsWithMatchedTNPair`

**Comment by Buwujiu** [comment]
Tested in QA, found issues, refer to https://github.com/icgc-argo/platform-api/issues/626.
