### ISSUE TITLE
Remove Family History from coreCompletion

### ISSUE THREAD

**Issue by demariadaniel** [icgc-argo/platform-api#650]
Early designs for Submitted Data included Family History as part of Core Completion.

These fields need to be removed from the API + UI as it is not part of the specification + not returned from the DB. This is populating empty fields which could lead to future confusion or bugs.

**Comment by demariadaniel** [comment]
API:
https://github.com/icgc-argo/platform-api/pull/649

UI:
https://github.com/icgc-argo/platform-ui/pull/2612

**Comment by Buwujiu** [comment]
@demariadaniel can you add a version label? thank you!

**Comment by Buwujiu** [comment]
Tested in staging, working as expected!

**Comment by Buwujiu** [comment]
Tested in prod, working as expected!
