### ISSUE TITLE
Update `Sample Registration Errors`

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-api#73]
https://wiki.oicr.on.ca/display/icgcargotech/Clinical+Submission+Validation+Errors 

Numbers 1-10 need updating in the UI response

**Comment by joneubank** [comment]
Most of this work was done in Clinical: https://github.com/icgc-argo/argo-clinical/pull/222

Also has gateway updates to handle this: https://github.com/icgc-argo/platform-api/pull/101

**Comment by rosibaj** [comment]
Tested - Errors are absolutely magical! Thanks @joneubank!!!!
